CLUSTER_NAME="${CLUSTER_NAME:-local}"
KUBE_CONTEXT="${KUBE_CONTEXT:-kind-${CLUSTER_NAME}}"
KIND_NETWORK="${KIND_NETWORK:-kind}"

REGISTRY_NAME="${REGISTRY_NAME:-kind-registry}"
REGISTRY_HOST="${REGISTRY_HOST:-localhost}"
REGISTRY_HOST_PORT="${REGISTRY_HOST_PORT:-5001}"
REGISTRY_CONTAINER_PORT="${REGISTRY_CONTAINER_PORT:-5000}"
REGISTRY_IMAGE="${REGISTRY_IMAGE:-docker.io/library/registry:2}"
REGISTRY_ADDRESS="${REGISTRY_HOST}:${REGISTRY_HOST_PORT}"

ARGOCD_NAMESPACE="${ARGOCD_NAMESPACE:-argocd}"
ARGOCD_VERSION="${ARGOCD_VERSION:-v3.4.6}"

ENVOY_GATEWAY_VERSION="${ENVOY_GATEWAY_VERSION:-v1.8.3}"
ENVOY_GATEWAY_NAMESPACE="${ENVOY_GATEWAY_NAMESPACE:-envoy-gateway-system}"
ENVOY_GATEWAY_NAME="${ENVOY_GATEWAY_NAME:-local-gateway}"
ENVOY_GATEWAY_LOCAL_PORT="${ENVOY_GATEWAY_LOCAL_PORT:-8080}"
